server:
  port: 8095
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: http://localhost:8097/
        predicates:
        - Path=/customers/**
        
      - id: product-service
        uri: http://localhost:8096/
        predicates:
        - Path=/products/**